### ISSUE TITLE
Installing Library

### ISSUE THREAD

**Issue by suprnrdy** [francisli/processing-restclient#5]
I'm not able to install this library with the Processing IDE.  There is no .JAR File.  Is there another way of doing this?

**Comment by MaxCelar** [comment]
Hi Francis. The download link (https://github.com/downloads/francisli/processing-http/http.zip) is not available anymore. Can you please provide a new link.
Thanks a lot,
Max

**Comment by francisli** [comment]
Hi @MaxCelar, you caught me by surprise, I didn't think anyone was still finding this library!

I just started updating it this last week, so the documentation is not yet updated, but here's an updated release:

https://github.com/francisli/processing-restclient/releases/download/1.0/restclient.zip

Unzip and drag the resulting folder into your Processing/libraries folder.

Note that the main library class name is now ```RESTClient``` not ```HTTPClient```. I'll be working on updating all the documentation now after this...

**Comment by MaxCelar** [comment]
Hi @francisli, thanks a lot for such a quick response, download link, and assistance. I'm no coder, but hopefully, I manage to collage something together for an art project. I came across your library when looking for a way to get Instagram feed into Processing. I've already managed to collage what I need for a part of the installation that contains a Twitter feed using twitter4j.  I've got some issues using your library to harvest Instagram feed though. Specifically with handling JSON data. 
I'm trying to make a code made by Augusitna Z (https://itp.nyu.edu/classes/creativecomputing-spring2015/instagram-api/) work:
`
import com.francisli.processing.restclient.*;
import java.util.List;
import java.util.Iterator;
import java.util.*;
 
PFont InstagramFont;
PImage backgroundimg;
PImage brand;
PImage userphoto;
PImage profilepicture;
 
String username;
String tag;
String[] tagStrings;
 
String comment;
 
RESTClient client;
JSONObject json;
JSONObject content;
JSONArray data;
JSONObject first;
JSONObject tags;

void setup() {
  size(580, 900);
  smooth();
  //backgroundimg = loadImage("globalgram_background.jpg");
  //brand = loadImage("iso.jpg");
 
  InstagramFont = loadFont("Helvetica-Bold-36.vlw");
 
  client = new com.francisli.processing.restclient.RESTClient(this, "api.instagram.com");
  client.useSSL = true;
 
 
}
 
void getGrams() {
    //// instantiate a new HashMap
  HashMap params = new HashMap();
  //// put key/value pairs that you want to send in the request
  params.put("access_token", "-----TOKEN HERE-----");
  params.put("count", "0");
  client.GET("/v1/tags/newyork/media/recent.json", params);
}
 
void responseReceived(HttpRequest request, HttpResponse response) {
  println(response.getContentAsString());
 
  //// we get the server response as a JSON object
  json = new JSONObject();
  content = new JSONObject();
  data = new JSONArray();
  first = new JSONObject();
  tags = new JSONObject();
  content = response.getContentAsJSONObject();
 
  //// get the "data" value, which is an array
  data = content.getJSONArray("data");
 
  //// get the first element in the array
  first = data.getJSONObject(0);
 
  //// the "user" value is another dictionary, from which we can get the "full_name" string value
  println(first.get("user").get("full_name").stringValue());
  //// the "caption" value is another dictionary, from which we can get the "text" string value
  //println(first.get("caption").get("text").stringValue());
  //// get profile picture
  println(first.get("user").get("profile_picture").stringValue());
  //// the "images" value is another dictionary, from which we can get different image URL data
  println(first.get("images").get("standard_resolution").get("url").stringValue());
 
  tags = first.get("tags");
  tagStrings = new String[tags.size()];
  for (int i = 0; i < tags.size(); i++) {
    tagStrings[i] = tags.get(i).stringValue();
  } 
 
  comment = first.get("caption").get("text").stringValue();
  username = first.get("user").get("full_name").stringValue();
 
  String profilepicture_url = first.get("user").get("profile_picture").stringValue();
  profilepicture = loadImage(profilepicture_url, "png");
 
  String userphoto_url = first.get("images").get("standard_resolution").get("url").stringValue();
  userphoto = loadImage(userphoto_url, "png");
 
 //noLoop();
}
 
 
void draw() {
  background(255);
  //imageMode(CENTER);
  //image(brand, 100, height/1.05);
 
  println(frameCount);
 
  if(frameCount % 1000 == 0){
    getGrams();
  }
 
  if (profilepicture != null) {
    image(profilepicture, 60, 70, 90, 90);
  }
  imageMode(CENTER);
  if (userphoto != null) {
    image(userphoto, width/2, height/2.25, 550, 550);
  }
 
  textFont(InstagramFont, 20);
  if (username != null) {
    text(username, 110, 115);
    fill(0);
  }
 
  textFont(InstagramFont, 15);
  if (comment != null) {
    text(comment, 15, 700, 550, 100);
    fill(0);
  }
 
 
}`
the problem seems to be with "get()" functions. I don't really understand what's going on.
I would really appreciate if you could assist me or direct me to useful tutorials as I've been unsuccessful finding any solutions to the problem. Thanks for your work, I can't really contribute with much knowledge in this case but would be ready to make a small donation if you give me your PayPal e-mail address. 

Thanks,
Max
